%YAML:1.0

#-------------------------------------
# System parameters. Adjust them!
#-------------------------------------

cartImageWidth: 1153
cartImageHeight: 1153
cartImageScale: 100.0 # Maximum distance at each azimuth scan in meters
startFrameTest: 0
lastFrameTest: 8282
localFramesMaxSize: 0 # Maximum frames stored in the local map window
# Loop closure option
loopClosure: 0 # Loop closure option
# center Mask Range
centerMaskRange: 3
# Track mode: 0 (track keyframe), 1 (track last k frames with KLT tracker)
trackMode: 1 

# Initial Pose
init_pose: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1, 0, 0,
           0, 1, 0,
           0, 0, 1]

pause: 0
loopRate: 0.2
descriptorOption: 2 # 1: CFAR, 2: SURF 3: ORB
ithFrame: 1 # Start from which Frame to perform matching

# New frame criteria
keyFrameDistance: 3.0
keyFrameAngle: 0.05

# Matching parameters
matcherOption: 0 # 0: Nearest Neighbour 1: FLANN 2: Brute force
LowesRatio: 0.7
cliqueDistThres: 2 # clique rigidity distance threshold
treeRadius: 40 # KD tree radius in pixel


# Path to read Radar Polar and Cartesian Image
datasetPath: /home/hong/Documents/VW_RADAR_DATASET/FoggyNew/FoggyNew6/
polarRadarImageAssociateFile: /home/hong/Documents/VW_RADAR_DATASET/FoggyNew/FoggyNew6/Navtech_Polar.txt
radarImagePolarFolderPath: /home/hong/Documents/VW_RADAR_DATASET/FoggyNew/FoggyNew6/radar_zfill_six/
radarImageCartesianFolderPath: /home/hong/Documents/VW_RADAR_DATASET/FoggyNew/FoggyNew6/1153_radar_cart/

# Path to GPS, IMU and Twist
gpsAssociateFile: /home/hong/Documents/VW_RADAR_DATASET/FoggyNew/FoggyNew6/GPS_IMU_Twist.txt
gpsimuFolderPath: /home/hong/Documents/VW_RADAR_DATASET/FoggyNew/FoggyNew6/GPS_IMU_Twist/

# Path to groundtruth
groundtruthFile: /home/hong/Documents/VW_RADAR_DATASET/FoggyNew/FoggyNew6/groundtruth_converted.txt

# Odometry result path
odometryResultFile: /home/hong/Documents/VW_RADAR_DATASET/FoggyNew/FoggyNew6/our_result_odometry.csv
# Path to store optimization result
g2oResult: /home/hong/Documents/g2o/radar_localization/

# Path to store log 
logPath: /home/hong/catkin_ws/src/radar_localization/logfile/

# CFAR parameters
viPointSize: 50
numberOfTrainCell: 80
numberOfGuardCell: 4
probabilityOfFalseAlarm: 0.1

# Oxford
oxfordRadius: 20
wedgeResolution: 20

# SURF parameters
minHessian: 800



# Current Pose optimization
optimizeStep: 20
huberWidth: 1
minMatchesBetweenFrames: 4
landmarkMinObservation: 2
landmarkInformation: 100
poseInformationXY: 10000
poseInformationYaw: 10000
twoFramesOptimization: 1
chiTwo: 200


# Symmetric transfer error optimization
convert2LocalFrame: 1
ceresORg2o: 0 # 1: ceres, 0 g2o:

# For visualization
pointCloudSize: 1
