%
% 
% Visualize all the map points generated by our radar SLAM
%
%%
close all;

sequence = '/media/hong/DiskC/Oxford_Radar_RobotCar_Dataset/2019-01-17-13-26-39-radar-oxford-10k/';
% sequence = '/media/hong/DiskD/RADIATE_DATASET/Loops/3_2020-02-10-15-15-02/';

csvfile = strcat(sequence, 'MapPoint.csv');
rows = readmatrix(csvfile);
nObsKLT = rows(:,2);
indexsKLT = find(nObsKLT>2);
mean(nObsKLT)
h1 = histogram(nObsKLT(indexsKLT),'Normalization','probability');
h1.BinEdges = [2:40];

hold on

csvfileIROS = strcat(sequence, 'MapPointIROS.csv');
rowsIROS = readmatrix(csvfileIROS);
nObsSURF = rowsIROS(:,2);
indexsSURF = find(nObsSURF>2);
mean(nObsSURF)
h2 = histogram(nObsSURF(indexsSURF),'Normalization','probability');
h2.BinEdges = [2:40];

lgd=legend('Tracking based', 'Matching based');
lgd.FontSize = 30;
xlabel('Number of observations per feature point.');
ylabel('Probability')
%%
% fig = figure;
% 
% ro_file = strcat(sequence ,'ro/keyframe/4/keyframe_pose.csv');
% ro = readmatrix(ro_file);
% ro = sortrows(ro);
% yaws_ro = ro(:,4)';
% poses_ro = zeros(3,3,size(ro,1));
% for i = 1:size(ro,1)
%         poses_ro(:,:,i) = [cos(yaws_ro(i)) -sin(yaws_ro(i)) ro(i,2);
%         sin(yaws_ro(i))  cos(yaws_ro(i)) ro(i,3);
%         0                0                   1   ];
% end
% x = reshape(poses_ro(1,3,:),[1 size(ro,1)]);
% y = reshape(poses_ro(2,3,:),[1 size(ro,1)]);
% plot(x,y,'b','LineWidth',4);
% hold on
% 
% 
% % plot(rows(:,2), rows(:,3), '.', 'MarkerSize',2.1, 'Color','k');
% scatter(rows(:,3), rows(:,4), 6, 'k', '.');
% 
% hold on
% %% Plot
% box off
% set(gca,'Units','normalized','Position',[0 0 1 1]);  %# Modify axes size
% set(gcf,'Units','pixels','Position',[0 0 1000 1000]);  %# Modify figure size
% set(gca,'XColor', 'none','YColor','none')
